### ISSUE TITLE
Outer loop gains and noise parameter are missing on autotown viewing page

### ISSUE THREAD

**Issue by mlyle** [d-ronin/autotown#1]
http://dronin-autotown.appspot.com/at/tune/ahFzfmRyb25pbi1hdXRvdG93bnIYCxILVHVuZVJlc3VsdHMYgICAgMCInQoM

**Comment by mlyle** [comment]
Woohoo issue #1.

**Comment by tracernz** [comment]
This done right?

**Comment by mlyle** [comment]
yes :D
