### ISSUE TITLE
Empty Stack Dump Should Be Rejected

### ISSUE THREAD

**Issue by tracernz** [d-ronin/autotown#12]
Two dumps my end failed to fetch, with 416 response from Google storage thing. Checked them in Cloud Console and noticed they both have the same filename/path, and it's 0 bytes...
http://dronin-autotown.appspot.com/at/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgJDVyNMKDA
http://dronin-autotown.appspot.com/at/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgJCxqboIDA

[So... the filename is the sha1 sum of the dump contents, that makes sense then.](https://github.com/d-ronin/autotown/blob/master/web.go#L402)
mike@tracer:~$ echo -n '' | openssl sha1
(stdin)= da39a3ee5e6b4b0d3255bfef95601890afd80709

da/39a3ee5e6b4b0d3255bfef95601890afd80709 is the filename. ;)

Should probably check the length of the dump is non-zero there and return 400.

The guy did manage to send a non-empty dump: http://dronin-autotown.appspot.com/at/crash/ahFzfmRyb25pbi1hdXRvdG93bnIWCxIJQ3Jhc2hEYXRhGICAgJD45egLDA

**Comment by dustin** [comment]
Huh, interesting.  So the crash sent properly base64 encoded nothingness?

**Comment by tracernz** [comment]
Yeah. Google cloud just refused to allow me to read nothing.. :(
